apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctfd-deployment
  labels:
    app: ctfd
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: ctfd
  template:
    metadata:
      labels:
        app: ctfd
    spec:
      containers:
      - name: ctfd
        image: team1nf1n1ty/ctfd
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ctfd-secret
              key: database-url

        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ctfd-secret
              key: secret-key

        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: ctfd-secret
              key: redis-url 
              
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ctfd-secret
              key: aws-access-key-id 

        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ctfd-secret
              key: aws-secret-access-key 

        - name: AWS_S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: ctfd-config
              key: aws-s3-bucket 

        - name: AWS_S3_ENDPOINT_URL
          valueFrom:
            configMapKeyRef:
              name: ctfd-config
              key: aws-s3-endpoint-url 
        
        - name: UPLOAD_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: ctfd-config
              key: upload-provider 
              
        - name: AWS_S3_REGION
          valueFrom:
            configMapKeyRef:
              name: ctfd-config
              key: aws-s3-region 

        - name: AWS_S3_CUSTOM_PREFIX
          valueFrom:
            configMapKeyRef:
              name: ctfd-config
              key: aws-s3-prefix 

        - name: UPLOAD_FOLDER
          valueFrom:
            configMapKeyRef:
              name: ctfd-config
              key: upload-folder

        - name: WORKERS
          valueFrom:
            configMapKeyRef:
              name: ctfd-config
              key: workers

        - name: LOG_FOLDER
          valueFrom:
            configMapKeyRef:
              name: ctfd-config
              key: log-folder

        - name: REVERSE_PROXY
          valueFrom:
            configMapKeyRef:
              name: ctfd-config
              key: reverse-proxy


        - name: ACCESS_LOG
          value: "-"

        - name: ERROR_LOG
          value: "-"

        volumeMounts:
        - name: log-volume
          mountPath: .data/CTFd/logs
          
        - name: uploads-volume
          mountPath: .data/CTFd/uploads
        
      volumes:
      - name: log-volume
      - name: uploads-volume
          
---
apiVersion: v1
kind: Service
metadata:
  name: ctfd-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: ctfd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30010
